CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  ?s ?p ?o .

  # Exclude persoon predicates handled by dedicated conversion files
  FILTER(!STRSTARTS(STR(?p), "http://data.vlaanderen.be/ns/persoon#"))

  # Exclude mandaat:isTijdspecialisatieVan handled by conversion file
  FILTER(?p != <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>)

  # Exclude foaf:firstName handled by conversion file (OP uses foaf:givenName)
  FILTER(?p != <http://xmlns.com/foaf/0.1/firstName>)

  # Exclude http persoon types (e.g. persoon:Geboorte) handled by type conversion
  FILTER(
    ?p != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ||
    !STRSTARTS(STR(?o), "http://data.vlaanderen.be/ns/persoon#")
  )
}
