PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu:   <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>
PREFIX organisatie: <http://lblod.data.gift/vocabularies/organisatie/>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  ?s a ?type ;
     ?p ?o .

  VALUES ?type {
    ext:OrganizationClassificationCode
    organisatie:BestuurseenheidClassificatieCode
  }

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    skos:prefLabel
  ))
}
