PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX person:  <http://www.w3.org/ns/person#>

# Loket Person.foaf:name = alternatieve-naam → OP persoon:gebruikteVoornaam.

CONSTRUCT {
  ?s persoon:gebruikteVoornaam ?name .
} WHERE {
  ?s a person:Person ;
     foaf:name ?name .
}
