version: '3.7'

services:
  yasgui:
    restart: "no"
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
#  database:
#    restart: "no"
  database:
    ports:
      - "8892:8890"
    restart: "no"
  migrations:
    restart: "no"
  mandatendatabank-consumer:
    restart: "no"
  leidinggevenden-consumer:
    restart: "no"
  persons-sensitive-consumer:
    restart: "no"
  subsidies-consumer:
    restart: "no"
