# https://binnenland.atlassian.net/browse/ABI-1399
# OP-canonical first name lives at foaf:givenName
# (persoon:gebruikteVoornaam in OP = "first-name-used" / alternative voornaam).
# Geslacht binds to the URI directly; the prefLabel join is wrapped in
# a nested OPTIONAL so the URI still counts when the code-list isn't
# in the warehouse.
PREFIX person:   <http://www.w3.org/ns/person#>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX dct:      <http://purl.org/dc/terms/>
PREFIX adms:     <http://www.w3.org/ns/adms#>
PREFIX prov:     <http://www.w3.org/ns/prov#>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX persoon:  <https://data.vlaanderen.be/ns/persoon#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>

SELECT DISTINCT
  ?persoon
  ?voornaam
  ?achternaam
  ?geboortedatum
  ?geslacht
  ?nationaliteit
WHERE {
  ?persoon a person:Person .

  OPTIONAL { ?persoon foaf:givenName ?voornaam . }
  OPTIONAL { ?persoon foaf:familyName ?achternaam . }

  OPTIONAL {
    ?persoon persoon:heeftGeboorte ?geboorteNode .
    ?geboorteNode persoon:datum ?geboortedatum .
  }

  OPTIONAL {
    ?persoon persoon:geslacht ?geslacht .
    OPTIONAL { ?geslacht skos:prefLabel ?geslachtLabel . }
  }

  OPTIONAL {
    ?persoon persoon:heeftNationaliteit ?nationaliteitUri .
    ?nationaliteitUri skos:prefLabel ?nationaliteit .
  }
}
