# https://binnenland.atlassian.net/browse/ABI-1384
PREFIX rov:  <http://www.w3.org/ns/regorg#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?status ?label
WHERE {
  ?org rov:orgStatus ?status .

  OPTIONAL { ?status skos:prefLabel ?label . }
}
