# https://binnenland.atlassian.net/browse/ABI-1390
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

SELECT DISTINCT
  ?BestuursorgaanURI
  ?WerkingsgebiedURI
WHERE {
  ?BestuursorgaanURI besluit:werkingsgebied ?WerkingsgebiedURI .
}
