# Workaround sprintF issue....
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/1> a <http://mu.semte.ch/vocabularies/ext/MandatarisStatusCode>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/2> a <http://mu.semte.ch/vocabularies/ext/BeleidsdomeinCode>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/3> a <http://data.vlaanderen.be/ns/mandaat#Mandataris>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/4> a <http://www.w3.org/ns/person#Person>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/5> a <http://www.w3.org/ns/org#Membership>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/6> a <http://data.vlaanderen.be/ns/mandaat#Fractie>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/7> a <http://data.vlaanderen.be/ns/mandaat#Mandaat>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/8> a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/9> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/10> a <http://mu.semte.ch/vocabularies/ext/BestuursorgaanClassificatieCode>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/11> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/12> a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    <http://dummy/fe2f5e9b-96b1-4700-a700-24ad999866e7/12> a <http://www.w3.org/ns/prov#Location>.
  }
}

# MANDATARIS-STATUS-CODE
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/MandatarisStatusCode>.
    ?s ?p ?o.
  }
}

# BELEIDSDOMEIN-CODE
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BeleidsdomeinCode>.
    ?s ?p ?o.
  }
}

# MANDATARIS
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/mandaat#Mandataris>.
    ?s ?p ?o.
  }
}

# PERSON
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/person#Person>.
    ?s ?p ?o.
  }
}

# MEMBERSHIP
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/org#Membership>.
    ?s ?p ?o.
  }
}

# FRACTIE
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/mandaat#Fractie>.
    ?s ?p ?o.
  }
}

# MANDAAT
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/mandaat#Mandaat>.
    ?s ?p ?o.
  }
}

# BESTUURSFUNCTIE-CODE
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>.
    ?s ?p ?o.
  }
}

# BESTUURSORGAAN
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    ?s ?p ?o.
  }
}

# BESTUURSORGAAN-CLASSIFICATIE-CODE
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuursorgaanClassificatieCode>.
    ?s ?p ?o.
  }
}

# BESTUURSEENHEID
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    ?s ?p ?o.
  }
}

# BESTUURSEENHEID-CLASSIFICATIE-CODE
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    ?s ?p ?o.
  }
}

# LOCATION
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/prov#Location>.
    ?s ?p ?o.
  }
}
