# Workaround sprintF issue....
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/1> a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/2> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/3> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/4> a <http://mu.semte.ch/vocabularies/ext/BestuursorgaanClassificatieCode>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/5> a <http://schema.org/ContactPoint>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/7> a <http://www.w3.org/ns/locn#Address>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/8> a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/9> a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/10> a <http://data.lblod.info/vocabularies/leidinggevenden/Functionaris>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/11> a <http://data.lblod.info/vocabularies/leidinggevenden/FunctionarisStatusCode>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/12> a <http://www.w3.org/ns/person#Person>.
    <http://dummy/6b92754b-c3b1-42b8-85c4-4ade83c57bd5/13> a <http://www.w3.org/ns/prov#Location>.
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuursorgaanClassificatieCode>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://schema.org/ContactPoint>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/locn#Address>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.lblod.info/vocabularies/leidinggevenden/Functionaris>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.lblod.info/vocabularies/leidinggevenden/FunctionarisStatusCode>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/person#Person>.
    ?s ?p ?o.
  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/prov#Location>.
    ?s ?p ?o.
  }
}