PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu:    <http://mu.semte.ch/vocabularies/core/>
PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX adms:  <http://www.w3.org/ns/adms#>
PREFIX person: <http://www.w3.org/ns/person#>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  ?s a person:Person ;
     ?p ?o .

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    dct:modified,
    foaf:familyName,
    adms:identifier
  ))

  FILTER NOT EXISTS { ?s ?p "" . }
}
