PREFIX cogs: <http://vocab.deri.ie/cogs#>
PREFIX task: <http://redpencil.data.gift/vocabularies/tasks/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX schema: <http://schema.org/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/system/jobs> {
    <http://data.lblod.info/id/scheduled-job/data-monitoring>
      a cogs:ScheduledJob ;
      mu:uuid "data-monitoring-scheduled-job" ;
      task:operation <http://redpencil.data.gift/id/jobs/concept/JobOperation/dataMonitoring> ;
      task:schedule <http://data.lblod.info/id/schedule/data-monitoring> .

    <http://data.lblod.info/id/schedule/data-monitoring>
      a task:CronSchedule ;
      schema:repeatFrequency "17 4 * * *" .
  }
}
