CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  ?s a ?type .
  ?s ?p ?o .
  VALUES ?type {
    <http://data.lblod.info/vocabularies/erediensten/BestuurVanDeEredienst>
    <http://data.lblod.info/vocabularies/erediensten/CentraalBestuurVanDeEredienst>
    <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>
    <http://www.w3.org/ns/regorg#RegisteredOrganization>
    <http://data.lblod.info/vocabularies/erediensten/RepresentatiefOrgaan>
    <http://data.lblod.info/vocabularies/erediensten/BetrokkenLokaleBesturen>
    <http://data.lblod.info/vocabularies/erediensten/PositieBedienaar>
    <http://www.w3.org/ns/org#Site>
    <http://www.w3.org/ns/locn#Address>
    <http://schema.org/ContactPoint>
    <http://www.w3.org/ns/adms#Identifier>
    <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator>
    <http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode>
    <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>
    <http://lblod.data.gift/vocabularies/organisatie/TypeEredienst>
    <http://lblod.data.gift/vocabularies/organisatie/BestuursorgaanClassificatieCode>
    <http://www.w3.org/ns/org#ChangeEvent>
    <http://lblod.data.gift/vocabularies/organisatie/Veranderingsgebeurtenis>
    <http://lblod.data.gift/vocabularies/organisatie/OrganisatieStatusCode>
    <http://lblod.data.gift/vocabularies/organisatie/TypeVestiging>
    <http://data.vlaanderen.be/ns/mandaat#Mandaat>
    <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie>
    <http://mu.semte.ch/vocabularies/ext/GeregistreerdeOrganisatieClassificatieCode>
    <http://lblod.data.gift/vocabularies/organisatie/BestuursfunctieCode>
    <http://data.lblod.info/vocabularies/leidinggevenden/FunctionarisStatusCode>
    <http://lblod.data.gift/vocabularies/organisatie/MandatarisStatusCode>
    <http://www.w3.org/ns/prov#Location>
  }
}